#!/bin/sh -e
#
# This program uses the `smileys` utility to retrieve the list of
# JeuxVideo.com smileys and will download them all in the current
# directory.
#

readonly PROGDIR=$(dirname "$0")
readonly SMILEYS="$PROGDIR/smileys"
readonly SMILEYS_IMG_URL='http://image.jeuxvideo.com/smileys_img/'

main() {
    "$SMILEYS" | while read code file; do
        printf '%15s %s\n' "$code" "$file"
        curl -so "$file" "$SMILEYS_IMG_URL/$file"
    done
}

main "$@"
