#!/bin/sh -e

readonly SMILEYS_IMG_URL='http://image.jeuxvideo.com/smileys_img/'

main() {
    while read file; do
        echo "$file"
        curl -so "$file" "$SMILEYS_IMG_URL/$file"
    done
}

main "$@"
